### ISSUE TITLE
Unable to load cluster status with Local Setup

### ISSUE THREAD

**Issue by sohailA-splore** [spotify/vispana#67]
After following the steps mentions in README.md, I am unable to view the vespa cluster status.

### Steps:
- Create a docker network
	docker network create --driver bridge vespanet
- Run Vespa within vespanet network and vespa-container hostname :
	docker run --detach --name vespa --network vespanet --hostname vespa-container --publish 8080:8080 --publish 19071:19071 vespaengine/vespa
- Run Vispana within vespanet network:
	docker run -p 4000:4000 --network vespanet vispana/vispana:latest
- Access Vispana in your browser via http://localhost:4000/ and specify the config node as http://vespa-container:19071`

<img width="1602" alt="Screenshot 2024-03-01 at 3 33 54 PM" src="https://github.com/vispana/vispana/assets/138469692/d03e31bc-7b21-433d-aa3d-cefcae4271c3">

**Comment by broknloop** [comment]
Hi @sohailA-splore , sorry for the delay!
I just went through the process of connecting to a local application and I managed to connect successfully to a localhost.
Are you able to index and query the vespa application you just tried to run?

**Comment by sohailA-splore** [comment]
Hi @broknloop ,
I am facing this issue when trying to use docker network. Otherwise it is working for me.

**Comment by fabianotex** [comment]
I'm facing the same issue. Getting the following error:

```
2024-09-17T15:19:21.213Z ERROR 1 --- [mcat-handler-53] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: java.lang.RuntimeException: Failed to get data from Vespa] with root cause

org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"error-code":"NOT_FOUND","message":"Session 3 does not contain a file at path '/services.xml'"}"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:112) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.client.StatusHandler.lambda$defaultHandler$3(StatusHandler.java:86) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.client.StatusHandler.handle(StatusHandler.java:146) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.applyStatusHandlers(DefaultRestClient.java:654) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.client.DefaultRestClient.readWithMessageConverters(DefaultRestClient.java:192) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.readBody(DefaultRestClient.java:641) ~[spring-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.body(DefaultRestClient.java:589) ~[spring-web-6.1.1.jar!/:6.1.1]
        at com.vispana.vespa.state.helpers.Request.requestGet(Request.java:10) ~[!/:0.0.1-SNAPSHOT]
        at com.vispana.vespa.state.assemblers.AppPackageAssembler.assemble(AppPackageAssembler.java:14) ~[!/:0.0.1-SNAPSHOT]
        at com.vispana.vespa.state.VespaStateClient.lambda$vespaState$4(VespaStateClient.java:33) ~[!/:0.0.1-SNAPSHOT]
        at java.base/java.util.concurrent.StructuredTaskScope$SubtaskImpl.run(StructuredTaskScope.java:889) ~[na:na]
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[na:na]
```

Vespa is operational and my team is using it just fine. Getting response from ports 19071 and 8080 via curl.

Any ideas?

Thanks.
